include "/etc/bind/named.conf.options";
// No incluimos named.conf.local aquí afuera si contiene zonas directas
// para evitar el error "all zones must be in views"

view "internal" {
    // Clientes de la red local del servidor y localhost
    match-clients { 10.1.0.0/24; 127.0.0.0/8; };
    recursion yes;

    zone "dominio.local" {
        type master;
        file "/etc/bind/zones/db.dominio.local";
    };

    zone "dominio.com" {
        type master;
        file "/etc/bind/zones/db.dominio.com.internal";
    };
};

view "external" {
    // Clientes que vienen de afuera (como LAN2 a través del NAT de R1)
    match-clients { any; };
    recursion yes;

    zone "dominio.com" {
        type master;
        file "/etc/bind/zones/db.dominio.com.external";
    };
};